[package]
name = "raving-wgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.0"
env_logger = "0.9"
log = "0.4"
wgpu = { version = "0.13", features = ["spirv"] }
bytemuck = { version = "1.4", features = [ "derive" ] }

image = "0.24"

rustc-hash = "1.1"
rhai = { version = "1.10.1", features = ["sync", "f32_float"]}

anyhow = "1.0"


[dev-dependencies]
pollster = "0.2"


[[example]]
name = "triangle"
path = "examples/triangle.rs"
